Algoritmo "notas"
// Disciplina   : [Linguagem e Lógica de Programação]
// Aluno : Samara de Souza 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/08/2024
Var
// Seção de Declarações das variáveis 

NOTAS: vetor [1..3] de real
PESOS: vetor [1..3] de real

resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo